#
#
# Copyright Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
ARG FLAVOR=cpu
FROM quay.io/lightspeed-core/rag-content-${FLAVOR}:latest as lightspeed-core-rag-builder
ARG RHDH_DOCS_VERSION="1.8"
ARG NUM_WORKERS=1

USER 0
WORKDIR /rag-content

COPY ./pyproject.toml ./

RUN uv sync --no-dev

# ADD THIS LINE to pre-download the required NLTK data
RUN python -c "import nltk; nltk.download('stopwords')"

COPY scripts/ .
# Modify script inplace to account for new path
RUN sed -i 's/scripts\///' get_rhdh_plaintext_docs.sh
RUN ./get_rhdh_plaintext_docs.sh $RHDH_DOCS_VERSION

FROM registry.access.redhat.com/ubi9/python-312-minimal:9.7@sha256:2ac60c655288a88ec55df5e2154b9654629491e3c58b5c54450fb3d27a575cb6
COPY --from=lightspeed-core-rag-builder /rag-content/rhdh-product-docs-plaintext/1.8/titles /product_docs
COPY --from=lightspeed-core-rag-builder /rag-content/rag-file-upload.py /rag-file-upload.py

USER 0
WORKDIR /

RUN mkdir /licenses
# Install single dependency required by upload script
RUN pip install --no-cache-dir requests 

COPY LICENSE /licenses/

# Labels for enterprise contract
LABEL com.redhat.component=rhdh-lightspeed-rag-content
LABEL description="Red Hat Developer Hub Lightspeed RAG content"
LABEL distribution-scope=private
LABEL io.k8s.description="Red Hat Developer Hub Lightspeed RAG content"
LABEL io.k8s.display-name="Red Hat Developer Hub Lightspeed RAG content"
LABEL io.openshift.tags="developerhub,rhdh,lightspeed,ai,assistant,rag"
LABEL name=rhdh-lightspeed-rag-content
LABEL release=1.8
LABEL url="https://github.com/redhat-ai-dev/rhdh-rag-content"
LABEL vendor="Red Hat, Inc."
LABEL version=0.0.1
LABEL summary="Red Hat Developer Hub Lightspeed RAG content"

USER 65532:65532

ENV LLAMA_STACK_URL="http://host.docker.internal:8321"
ENV DOCS_DIR="/product_docs"

ENTRYPOINT ["python", "rag-file-upload.py"]