FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7@sha256:161a4e29ea482bab6048c2b36031b4f302ae81e4ff18b83e61785f40dc576f5d

COPY vector_db /rag-content/vector_db
COPY embeddings_model /rag-content/embeddings_model

USER 65532:65532